choco upgrade chocolatey -y
choco upgrade 7zip -y
choco upgrade wireshark -y
choco upgrade nmap -y
choco upgrade powertoys -y
choco upgrade powershell-core -y
choco upgrade openssh -y
choco upgrade nodejs -y
choco upgrade mkcert -y
choco install gnuplot -y
