version: "3"

services:
  proxy:
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ./proxy:/etc/nginx/conf.d
      - ./certs:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"