version: "3"

services:
  portainer:
    image: portainer/portainer-ce:alpine
    restart: always
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  jiraroadmap:
    image: registry.gitlab.com/vaeit/jiraroadmap:latest
    restart: always
    volumes:
      - ./roadmapconf:/app/conf
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./proxy:/etc/nginx/conf.d
      - ./certs:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
  
volumes:
  portainer_data:
