version: "2"

services:
  portainer:
    image: portainer/portainer
    restart: always
    ports:
      - '9443:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs:/certs
      - portainer_data:/data
    command:
      -H unix:///var/run/docker.sock
      --ssl
      --sslcert /certs/mycert.crt
      --sslkey /certs/mycert.key
  jiraroadmap:
    image: walljm/roadmap:latest
    restart: always
    ports:
      - "7443:443"
    volumes:
      - ./roadmapconf:/app/conf

      
volumes:
  portainer_data:
