# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.hostname = "gitlab"
  
  config.vm.provider "hyperv" do |h|
    h.vmname = "GitLab_Ubuntu1804"
    h.vm_integration_services = {
      guest_service_interface: true,
      heartbeat: true,
      key_value_pair_exchange: true,
      shutdown: true,
      time_synchronization: true,
      vss: true,
    }
  end

  
  config.vm.provision "shell", inline: <<-SHELL
    set -eux

    sudo apt-get update
    sudo apt-get install -y curl openssh-server ca-certificates

    curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | sudo bash
    sudo EXTERNAL_URL="http://gitlab.lan" apt-get install gitlab-ee -y
    sudo gitlab-ctl pg-upgrade
    sudo rm -rf /var/opt/gitlab/postgresql/data.<old_version>
    sudo rm -f /var/opt/gitlab/postgresql-version.old
    
  SHELL
  
end